# This is default jargon that you can use. Feel free to change it. See: https://boogi.netlify.app/editing/rich_content/abbreviations
'Alexa&#x27;s CV2 Docs':
  name: Alexa&#x27;s CV2 Docs
  long_name: Alexa&#x27;s Circuits V2 Docs
  description: This website is dedicated to explain everything you can do with Rec Room&#x27;s New Circuits v2 or CV2 system
